use crate::types::*;

// lalrpop 里的约定
grammar;

// 约束 lexer 的行为
match {
  // 跳过空白符和注释
  r"\s*" => {},
  r"//[^\n\r]*[\n\r]*" => {},
  r"/\*([^*]|\*+[^*/])*\*+/" => {},
  // 剩下的情况采用默认方式处理
  _
}

// 定义 CompUnit, 其返回值类型为 String
// parser 在解析完成后的行为是返回 FuncDef 的值
pub CompUnit: CompUnit = <func_def: FuncDef> => CompUnit {<>};

// 同上, 不解释
FuncDef: FuncDef = {
  <func_type: FuncType> <ident: Ident> "(" ")" <block: Block> => {
    FuncDef {<>}
  }
}

FuncType: FuncType = "int" => FuncType::Int;

Block: Block = "{" <stmt: Stmt> "}" => Block {<>};

Stmt: Stmt = "return" <exp: Exp> ";" => Stmt {<>};

Exp: Exp = <expr: AddExp> => Exp {<>};

UnaryOp: UnaryOp = {
  "+" => UnaryOp::Plus,
  "-" => UnaryOp::Minus,
  "!" => UnaryOp::Not,
};

PrimaryExp: PrimaryExp = {
  <num: Number> => PrimaryExp::Number(num),
  "(" <exp: Exp> ")" => PrimaryExp::Parenthesized(Box::new(exp)),
};

UnaryExp: UnaryExp = {
  <op: UnaryOp> <exp: UnaryExp> => UnaryExp::Unary{op, expr: Box::new(exp)}  ,
  <primary: PrimaryExp> => UnaryExp::Primary(primary),
};

MulOp: MulOp = {
  "*" => MulOp::Mul,
  "/" => MulOp::Div,
};

AddOp: AddOp = {
    "+" => AddOp::Plus,
    "-" => AddOp::Minus,
};

MulExp: MulExp = {
  <mulexpr: MulExp> <op: MulOp> <expr: UnaryExp> => MulExp::Mul { mulexpr: Box::new(mulexpr), op, expr: Box::new(expr) },
  <unary: UnaryExp> => MulExp::Unary(unary),
};

AddExp: AddExp = {
  <addexpr: AddExp> <op: AddOp> <expr: MulExp> => AddExp::Add { addexpr: Box::new(addexpr), op, expr: Box::new(expr) },
  <unary: UnaryExp> => AddExp::Mul(MulExp::Unary(unary)),
};


Number: i32 = <num: IntConst> => <>;

// 如果匹配到标识符, 就返回这个字符串
// 一对尖括号在此处指代的是正则表达式匹配到的字符串 (&str)
// 关于尖括号到底代表什么, 请 RTFM
Ident: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

// 对整数字面量的处理方式: 把匹配到的字符串按对应进制转换成数字
IntConst: i32 = {
  r"[1-9][0-9]*" => i32::from_str_radix(<>, 10).unwrap(),
  r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
  r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
}
